### PR TITLE
[EJBCLIENT-216] Fix generation of clustering-related ServiceURLs

### PR DESCRIPTION
**Pull request by rachmatowicz**
This PR makes the following changes:
* when a topology update arrives, creates one abstract ServiceURL to represent each node in the cluster, and multiple corresponding concrete ServiceURLs to represent the possible client mappings and target URIs associated with that node

This allows performLocatedAction to discover the nodes in a cluster as abstract ServiceURLs and in a second step to resolve them to concrete ServiceURLs.

See this issue for details: https://issues.jboss.org/browse/EJBCLIENT-216

### CODE REVIEW

**Comment by rachmatowicz** [comment]
David, this is my first draft of this PR. I am still working on it but wanted you to be able to look at it  to see if you agree with the basic approach. There is an issue with affinity which I need to look at, so please don't merge for now.

**Comment by dmlloyd** [comment]
Looks reasonable so far.

**Comment by rachmatowicz** [comment]
I was trying to write a test case for this by resurrecting DummyServer, but it's going to take me longer than expected. I don't plan any more changes so you can merge now if you like or wait until I get DummyServer working.

**Comment by dmlloyd** [comment]
@rachmatowicz there's a "real" server in the code base now that you can use instead, by providing an Association implementation.

**Comment by rachmatowicz** [comment]
You mean RemoteEJBService(Association, RemotingTransactionService)? This is what I was looking at using...

**Pull request merged**
