### PR TITLE
refactored code with renaming few variables and introducing modularization in some files

### PR DESCRIPTION
**Pull request by nmistry45**
Hi, 
I have refactored files by renaming variables, extracting methods, and classes for better modularization.

### CODE REVIEW

**Comment by chengfang** [comment]
@nmistry45 thanks for submitting the PR. Code changes like code style, formatting, minor refactoring can make it hard to diff against previous versions and port the fix to older versions in the future. So please limit the changes to what's necessary to fix the problem.

**Comment by nmistry45** [comment]
> 

Hey, sure. Will do that.
Please let me know for further changes.

**Comment by chengfang** [comment]
I see pretty all the changes are reformatting, rearrangement of class and methods, which make it hard for us to track the real functionality and behavior changes across versions. For that reason, we usually refrain from make such changes.

**Comment by nmistry45** [comment]
> I see pretty all the changes are reformatting, rearrangement of class and methods, which make it hard for us to track the real functionality and behavior changes across versions. For that reason, we usually refrain from make such changes.

Hi,
Actually, some of the changes were refactoring applied to remove some of the design smells and stuff.
I understand it makes difficult for you and I'm sorry for that.
Do give it a try and please let me know for any further changes.

**Pull request closed without merging**
